services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: devsrch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Chicago23
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: ./my_docker_app  # Указываем правильный путь
    container_name: django_app
    command: gunicorn --bind 0.0.0.0:4000 my_docker_app.wsgi:application
    volumes:
      - ./my_docker_app:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:Chicago23@db:5432/devsrch

volumes:
  pgdata:
